### ISSUE TITLE
Thundering heard

### ISSUE THREAD

**Issue by confuser** [medikoo/memoize#29]
memoize doesn't protect against a cache miss storm and can take down a high traffic site quite easily

E.g.
http://www.percona.com/blog/2010/09/10/cache-miss-storm/

http://en.wikipedia.org/wiki/Thundering_herd_problem

**Comment by medikoo** [comment]
@confuser if I understand problem accurately it surely protects.

Firstly JS is single threaded, there's no way for two clients try to access same item at _same time_. In all cases it'll be one event after another, and second and latter ones will always get cached result.

It's only _asynchronous_ requests, where such vulnerability may take place, but memoizee is bulletproof against that. After first request is initialized, all latter requests which are after same thing are put on hold until that one resolves. There's no scenario when same request is invoked multiple times because previous one didn't resolve yet.

If you still feel I miss something, please elaborate. Thanks!
